#pragma config(Sensor, S1,     Colour,         sensorEV3_Color)
#pragma config(Sensor, S2,     Ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S4,     Gyro,           sensorEV3_Gyro)
#pragma config(Motor,  motorB,          RightM,        tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          LeftM,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int nMotorSpeed = 15;
int black = 4;
int white = 60;
int sensitivity = 3;

task lineFollow(){
	while (abs(getGyroDegrees(Gyro)) < 7)
{
		int mathRight = getColorReflected(Colour)-black*sensitivity+nMotorSpeed;
		int mathLeft = white-getColorReflected(Colour)*sensitivity+nMotorSpeed;
		setMotorSpeed(RightM, mathRight);
		setMotorSpeed(LeftM, mathLeft);
		wait1Msec(10);
		//Datalogging
		datalogAddValue(1, getGyroDegrees(Gyro));
		datalogAddValue(2, getColorReflected(Colour));
	}
}

task main()
{
	resetGyro(Gyro);
	startTask(lineFollow);
}
