#pragma config(Sensor, S1,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S2,     Gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S3,     Ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     Colour,         sensorEV3_Color)
#pragma config(Motor,  motorB,          LeftM,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RightM,        tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMotorBrakeMode(LeftM,motorBrake);
	setMotorBrakeMode(RightM,motorBrake);

	//Potreba kalibrovat
	int speed = 70;
	int speedTurn = 70;
	int speedTurnNeg = -70;
	int waitTurn = 345;
	int speedBack = -50;
	int waitBack = 380;
	int waitFwd = 840;
	float USD = 20.0;

	while(true){
		setMotorSpeed(RightM, 0);
		setMotorSpeed(LeftM, 0);

		if(getUSDistance(Ultrasonic)>USD){
			setMotorSpeed(LeftM, speedTurnNeg);
			setMotorSpeed(RightM, speedTurn);
			wait1Msec(waitTurn);
		}

		if(getTouchValue(Touch)){
			setMotorSpeed(LeftM, speedBack);
			setMotorSpeed(RightM, speedBack);
			wait1Msec(waitBack);

			setMotorSpeed(LeftM, speedTurn);
			setMotorSpeed(RightM, speedTurnNeg);
			wait1Msec(waitTurn);
		}

		setMotorSpeed(LeftM, 0);
		setMotorSpeed(RightM, 0);
		wait1Msec(10);

		setMotorSpeed(LeftM, speed);
		setMotorSpeed(RightM, speed);
		wait1Msec(waitFwd);

		//gyroskop kontrola if--> break
	}
}
