#pragma config(Sensor, S1,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S2,     Gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S3,     Ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     Colour,         sensorEV3_Color)
#pragma config(Motor,  motorB,          LeftM,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RightM,        tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int MotorSpeed = 50;
	float kP = 1.55;
	float kI = 0.0;
	float kD = 0.0;
	float lastError = 0;
	int midpoint = 40;
	float error = 0;
	float derivative = 0;
	float integral = 0;
	float correction = 0;
	float correctionP = 0;
	float correctionI = 0;
	float correctionD = 0;

	while(true){
		error = midpoint - getColorReflected(Colour);
		derivative = error - lastError;
		integral = integral + error;
		correctionP = kP*error;
		correctionI = kI*integral;
		correctionD = kD*derivative;
		correction = round(correctionP + correctionI + correctionD);
		setMotorSpeed(LeftM, MotorSpeed+correction);
		setMotorSpeed(RightM, MotorSpeed-correction+10);
		lastError = error;
		//continue
	}
}
