#pragma config(Sensor, S1,     Colour,         sensorEV3_Color)
#pragma config(Sensor, S2,     Ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S4,     Gyro,           sensorEV3_Gyro)
#pragma config(Motor,  motorB,          RightM,        tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          LeftM,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int speed = 30;
	int midpoint = 60;
	float integral = 0;
	float kP = 1;
	float kI = 1;
	float kD = 1;
	int dt = 20;
	int lastError = 0;

	while(true){
		int error = midpoint - getColorReflected(Colour);
		integral = integral + error*dt;
		float derivative = (error - lastError)/dt;
		float correction = kP*error + kI*integral + kD*derivative;
		setMotorSpeed(LeftM, speed + correction);
		setMotorSpeed(RightM, speed - correction);
		lastError = error;
		wait1Msec(dt);
	}

}
