#pragma config(Sensor, S1,     Colour,         sensorEV3_Color)
#pragma config(Sensor, S2,     Ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S4,     Gyro,           sensorEV3_Gyro)
#pragma config(Motor,  motorB,          RightM,        tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          LeftM,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int nMotorSpeedSetting = 30;
float nPfactor = 0.3;
int grey = 50;

task main()
{
  float error;
  while (true)
  {
    error = getColorReflected(Colour) - grey;
    setMotorSpeed(LeftM, nMotorSpeedSetting - round(error * nPfactor));
    setMotorSpeed(RightM, nMotorSpeedSetting + round(error * nPfactor));
    wait1Msec(50);
  }
}
