#pragma config(Sensor, S1,     Colour,         sensorEV3_Color)
#pragma config(Sensor, S2,     Ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S4,     Gyro,           sensorEV3_Gyro)
#pragma config(Motor,  motorB,          RightM,        tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          LeftM,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int nMotorSpeedSetting = 20;
float nPfactor = 2;
int grey = 30;

task main()
{
	float lastError = 0;
  float error;
  error = SensorValue[Colour] - grey;
  while (true)
  {
    error = (SensorValue[Colour] - grey + lastError)/2;
    motor[LeftM] = nMotorSpeedSetting - round(error * nPfactor);
    motor[RightM] = nMotorSpeedSetting + round(error * nPfactor);
    lastError = error;
    wait1Msec(30);
  }
}
