#pragma config(Sensor, S1,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S2,     Gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S3,     Ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     Colour,         sensorEV3_Color)
#pragma config(Motor,  motorB,          LeftM,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RightM,        tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
	float US = getUSDistance(Ultrasonic);
		datalogAddValue(0, US);
		if(getTouchValue(Touch)){
			//Couvnout
			setMotorSpeed(RightM, -40);
			setMotorSpeed(LeftM, -40);
			wait1Msec(300);
			//Otocit
			setMotorSpeed(RightM, - 40);
			setMotorSpeed(LeftM, 40);
			wait1Msec(400);
			}
		if (US > 7.0 && US < 10.0){
			setMotorSpeed(LeftM, 40);
			setMotorSpeed(RightM, 40);
		}
		if(US < 7.0){
			setMotorSpeed(LeftM, 40);
			setMotorSpeed(RightM, 30);
		}
		if(US > 10.0){
			setMotorSpeed(LeftM, 30);
			setMotorSpeed(RightM, 40);
		}
	}
}
