#pragma config(Sensor, S1,     Colour,         sensorEV3_Color)
#pragma config(Sensor, S2,     Ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S4,     Gyro,           sensorEV3_Gyro)
#pragma config(Motor,  motorB,          RightM,        tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          LeftM,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float rightEmpty = 20.0;
int nSpeed = 40;
int nSpeedTurn = -50;
int nSpeedTurnNeg = 30;
int turnTime = 550;

task mazeSolve(){
	while(abs(getGyroDegrees(Gyro)) < 10){
		if (getTouchValue(Touch)){
			//Couvnout
			setMotorSpeed(RightM, nSpeedTurn);
			setMotorSpeed(LeftM, nSpeedTurn);
			wait1Msec(500);
			//Otocit
			setMotorSpeed(RightM, nSpeedTurn);
			setMotorSpeed(LeftM, nSpeedTurnNeg);
			wait1Msec(turnTime);
		}
		if(getUSDistance(Ultrasonic) < rightEmpty){
			//jed rovni
			setMotorSpeed(RightM, nSpeed);
			setMotorSpeed(LeftM, nSpeed);
			wait1Msec(500);
		}
		else{
			//Toc doleva
			setMotorSpeed(RightM, nSpeed);
			setMotorSpeed(LeftM, 10);
			wait1Msec(100);
		}
		//Datalogging
		datalogAddValue(1, getGyroDegrees(Gyro));
		datalogAddValue(2, getUSDistance(Ultrasonic));
	}
}

task main()
{
	resetGyro(Gyro);
	startTask(mazeSolve);
}
