#pragma config(Sensor, S1,     Colour,         sensorEV3_Color)
#pragma config(Sensor, S2,     Ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S4,     Gyro,           sensorEV3_Gyro)
#pragma config(Motor,  motorB,          RightM,        tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          LeftM,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int nMotorSpeed = 80;
int nMotorSpeedNeg = -40;
int black = 60;

task lineFollow(){
	while (true)
	{
		if(getColorReflected(Colour) < black){
			setMotorSpeed(RightM, nMotorSpeedNeg);
			setMotorSpeed(LeftM, nMotorSpeed);
			wait1Msec(10);
		}
		else{
			setMotorSpeed(RightM,nMotorSpeed+30);
			setMotorSpeed(LeftM,nMotorSpeedNeg+30);
			wait1Msec(30);
		}
		datalogAddValue(1, getGyroDegrees(Gyro));
		datalogAddValue(2, getColorReflected(Colour));
	}

};

task main()
{
	resetGyro(Gyro);
	startTask(lineFollow);
}
