#pragma config(Sensor, S1,     Colour,         sensorEV3_Color)
#pragma config(Sensor, S2,     Ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S4,     Gyro,           sensorEV3_Gyro)
#pragma config(Motor,  motorB,          RightM,        tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          LeftM,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
bool gyroResetReady = true;

task gyroReset(){
	sleep(15000);
	resetGyro(Gyro);
	gyroResetReady = true;
}

task main()
{
	int CnMotorSpeed = 50;
	float CkP = 25.0;
	float CkI = 0.0;
	float CkD = 0.0;
	float ClastError = 0;
	float Cmidpoint = 5.15;
	float Ccaptured = 0;
	float Cerror = 0;
	float Cderivative = 0;
	float Cintegral = 0;
	float Ccorrection = 0;
	bool onRamp = false;
	resetGyro(Gyro);

	while(true){
		Ccaptured = getColorReflected(Colour)/6.9;
		Cerror = Cmidpoint - Ccaptured;
		Cderivative = Cerror - ClastError;
		Cintegral = Cintegral + Cerror;
		Ccorrection = CkP*Cerror + CkI*Cintegral + CkD*Cderivative;
		setMotorSpeed(LeftM, CnMotorSpeed+Ccorrection);
		setMotorSpeed(RightM, CnMotorSpeed-Ccorrection);
		ClastError = Cerror;
		//datalogging
		datalogAddValue(0, getGyroDegrees(Gyro));
		datalogAddValue(1, Cerror);
		datalogAddValue(2, Ccorrection);
		//continue
		if(abs(getGyroDegrees(Gyro)) > 7){
			if(onRamp){
				onRamp = true;
				wait1Msec(100);
				resetGyro(Gyro);
			}
			else {
					onRamp = false;
					wait1Msec(200);
					resetGyro(Gyro);
					break;
			}
		}
		if (gyroResetReady){
			startTask(gyroReset);
		}
	}
	/*
	float rightEmpty = 20.0;
	int nSpeed = 40;
	int nSpeedTurn = -50;
	int nSpeedTurnNeg = 30;
	int turnTime = 550;
	resetGyro(Gyro);

	while(true){
		if (getTouchValue(Touch)){
			//Couvnout
			setMotorSpeed(RightM, nSpeedTurn);
			setMotorSpeed(LeftM, nSpeedTurn);
			wait1Msec(200);
			//Otocit
			setMotorSpeed(RightM, nSpeedTurn);
			setMotorSpeed(LeftM, nSpeedTurnNeg);
			wait1Msec(turnTime);
		}
		if(getUSDistance(Ultrasonic) < rightEmpty){
			//jed rovni
			setMotorSpeed(RightM, nSpeed);
			setMotorSpeed(LeftM, nSpeed);
			wait1Msec(turnTime);
		}
		else{
			//Toc doleva
			wait1Msec(250);
			setMotorSpeed(RightM, nSpeedTurnNeg);
			setMotorSpeed(LeftM, nSpeedTurn);
			wait1Msec(500);
			setMotorSpeed(RightM, nSpeed);
			setMotorSpeed(LeftM, nSpeed);
			wait1Msec(turnTime);
		}
		if(abs(getGyroDegrees(Gyro)) > 90){
			if(onRamp){
				onRamp = true;
				resetGyro(Gyro);
			}
			else {
				onRamp = false;
				resetGyro(Gyro);
				break;
			}
		}
	}

	Cerror = 0;
	Cderivative = 0;
	Ccorrection = 0;
	CcorrectionP = 0;
	CcorrectionD = 0;

	while(true){
	Cerror = Cmidpoint - getColorReflected(Colour);
	Cderivative = Cerror - ClastError;
	CcorrectionP = CkP*Cerror;
	CcorrectionD = CkD*Cderivative;
	Ccorrection = CcorrectionP + CcorrectionD;
	setMotorSpeed(LeftM, CnMotorSpeed*Ccorrection);
	setMotorSpeed(RightM, CnMotorSpeed);
	ClastError = Cerror;
	//datalogging
	datalogAddValue(0, Ccorrection);
	datalogAddValue(1, CcorrectionP);
	datalogAddValue(2, CcorrectionD);
	}
	*/
}
