#pragma config(Sensor, S1,     Colour,         sensorEV3_Color)
#pragma config(Sensor, S2,     Ultrasonic,     sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     Touch,          sensorEV3_Touch)
#pragma config(Sensor, S4,     Gyro,           sensorEV3_Gyro)
#pragma config(Motor,  motorB,          RightM,        tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          LeftM,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	bool onRamp = false;
	int error;
	float integral;
	float derivative;
	float turn;
	int lasterror;
	float kP = 50;
	float kI = 0.0;
	float kD = 0;
	int offset = 10;
	int tP = 50;

	while(true){
		error = getColorReflected(Colour) - offset;
		integral = integral + error;
		derivative = error - lasterror;
		turn = kP * error + kI * integral + kD * derivative;
		setMotorSpeed(RightM, tP + round(turn));
		setMotorSpeed(LeftM, tP - round(turn));
		lasterror = error;
		//datalogging
		datalogAddValue(0, getGyroDegrees(Gyro));
		//continue
		if(abs(getGyroDegrees(Gyro)) > 7){
			if(onRamp){
				onRamp = true;
				wait1Msec(100);
				resetGyro(Gyro);
			}
			else {
				onRamp = false;
				wait1Msec(200);
				resetGyro(Gyro);
				break;
			}
		}
	}
}
